name: Run Flexiroam Script Every 12 Hours

on:
  schedule:
    # Run every 12 hours at minute 0
    - cron: '0 */24 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flexiroam script with timeout
        run: timeout 300s python Flexiroam_FreePlan.py  # Run for 5 minutes (300 seconds) then force stop
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
